version: "3.7"

services:
  traefik:
    image: traefik:${traefik_image_tag}
    container_name: traefik
    command:
      - "--api.insecure=true"                
      - "--log.level=DEBUG"                  
      - "--providers.docker=true"             
      - "--entrypoints.http.address=:80" 
      - "--entrypoints.https.address=:443"   
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=test@example.com"
      - "--certificatesresolvers.myresolver.acme.storage=/acme.json"   
    ports:
      - "80:80"                             
      - "443:443"                        
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro" 
      - "./acme.json:/acme.json"
    networks:
      - web_net
    labels:
      - "traefik.http.routers.api.rule=Host(`${traefik_domain}`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.entrypoints=https"
      - "traefik.http.routers.api.tls.certresolver=myresolver"
      - "traefik.http.middlewares.auth.basicauth.users=admin:$$apr1$$KgleTQnt$$cs/JcgT5jFDHwhPHXNXkB1"
      - "traefik.http.routers.api.middlewares=auth"
  nexus:
    image: sonatype/nexus3:${nexus_image_tag}
    container_name: nexus
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web_net"
      - "traefik.http.routers.repo.entrypoints=http"
      - "traefik.http.routers.repo.rule=Host(`${nexus_domain}`)"
      - "traefik.http.routers.repo.service=repo-secure"
      - "traefik.http.routers.repo.middlewares=https-redirect"
      - "traefik.http.routers.repo-secure.entrypoints=https"
      - "traefik.http.routers.repo-secure.rule=Host(`${nexus_domain}`)"
      - "traefik.http.routers.repo-secure.tls=true"
      - "traefik.http.routers.repo-secure.tls.options=default"
      - "traefik.http.routers.repo-secure.tls.certresolver=mycert"
      - "traefik.http.routers.repo-secure.service=repo-secure"
      - "traefik.http.services.repo-secure.loadbalancer.server.port=8081"


      #docker registery
      - "traefik.http.routers.nexusdocker.entrypoints=http"
      - "traefik.http.routers.nexusdocker.rule=Host(`${docker_main_domain}`)"
      - "traefik.http.routers.nexusdocker.middlewares=https-redirect"
      - "traefik.http.routers.nexusdocker-secure.entrypoints=https"
      - "traefik.http.routers.nexusdocker.service=nexusdocker-secure"
      - "traefik.http.routers.nexusdocker-secure.rule=Host(`${docker_main_domain}`)"
      - "traefik.http.routers.nexusdocker-secure.tls=true"
      - "traefik.http.routers.nexusdocker-secure.tls.options=default"
      - "traefik.http.routers.nexusdocker-secure.tls.certresolver=mycert"
      - "traefik.http.routers.nexusdocker-secure.service=nexusdocker-secure"
      - "traefik.http.services.nexusdocker-secure.loadbalancer.server.port=8085"

      # - "traefik.http.routers.nexus.entrypoints=http"
      # - "traefik.http.routers.nexus.rule=Host(`${nexus_domain}`)"
      # - "traefik.http.routers.nexus.middlewares=https-redirect"
      # - "traefik.http.routers.nexus.service=nexusmirror-secure"
      # - "traefik.http.routers.nexus-secure.entrypoints=https"
      # - "traefik.http.routers.nexus-secure.rule=Host(`${nexus_domain}`)"
      # - "traefik.http.routers.nexus-secure.tls=true"
      # - "traefik.http.routers.nexus-secure.tls.options=default"
      # - "traefik.http.routers.nexus-secure.tls.certresolver=mycert"
      # - "traefik.http.routers.nexus-secure.service=nexusmirror-secure"
      # - "traefik.http.services.nexus-secure.loadbalancer.server.port=8084"
      # - "traefik.enable=true"
      # - "traefik.http.routers.nexus.rule=Host(`${nexus_domain}`)" 
      # - "traefik.http.services.nexus.loadbalancer.server.port=8081" 

      # - "traefik.http.routers.nexusdocker.entrypoints=http"
      # - "traefik.http.routers.nexusdocker.rule=Host(`${docker_main_domain}`)"
      # - "traefik.http.services.nexusdocker.loadbalancer.server.port=8085"
    volumes:
      - nexus-data:/nexus-data
    networks:
      - web_net

volumes:
  nexus-data:

networks:
  web_net:
    external: true
